### ISSUE TITLE
Make it possible to compress and/or hide the provenance graph

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/intent-system#255]
It should be possible to make the provenance graph really skinny (20 pixels, just icons, no labels) and/or hide it completely.

**Comment by ZachCutler04** [comment]
@alexsb Do you want the label only view to reduce the width of the provenance vis? This makes sense to me, I probably should have done that originally

**Comment by alexsb** [comment]
The icon only view you mean? Yes.

**Comment by ZachCutler04** [comment]
@alexsb Finished this, though due to the nature of the page nothing really happens, the icons just no longer look left aligned. Unfortunately changing the formatting of the page when this happens is a bit too far into react world for me currently. I would suggest probably changing it back so that switching to icon only does not affect the width for now

**Comment by kirangadhave** [comment]
i will fix this. This is easy with CSS

**Comment by kirangadhave** [comment]
We are now compressing the graph, so closing this for now.
